name: Bug Report
description: Report an error, crash or weird ass behavior
title: "[BUG] "
labels: "bug"
body:

  - type: markdown
    attributes:
      value: Report an error, crash or weird ass behavior

  - type: dropdown
    attributes:
      label: Report Category
      description: What version of our software are you running?
      options:
        - Weird Shit
        - Warning
        - Error
        - Crash
        - Corruption
        - Security
      default: 0
    validations:
      required: true
