name: Bug Report
description: Report an error, crash or weird ass behavior
title: "[BUG] "
labels: "bug"
body:

  - type: markdown
    attributes:
      value: Report an error, crash or weird ass behavior
