name: Bug Report
description: Report an error, crash or weird ass behavior
title: "[BUG] "
labels: "bug"
body:

  - type: markdown
    attributes:
      value: Report an error, crash or weird ass behavior

  - type: dropdown
    attributes:
      label: Report Category
      options:
        - "Weird Shit"
        - Warning
        - Error
        - Crash
        - Corruption
        - Security
        default: 0
    validations:
      required: true

  - type: input
    attributes:
      label: Description
      description: What's happening that you think should not happen?
      placeholder: Player is walking funny
    validations:
      required: true

  - type: input
    attributes:
      label: Expected Behavior
      description: What do you think should happen instead?
      placeholder: Player should walk cool
    validations:
      required: true
